# .github/workflows/check-pull-request.yml
name: Check Pull Request

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1.7.12

      - name: Linting and Build Check🧹
        run: yarn pr

      - name: Build
        run: yarn build:ncc

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          branch: main
          extra_plugins: |
            @semantic-release/git
            @semantic-release/changelog
          dry_run: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
